package com.SharkTank.hanspee;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Hanspee {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form keyboard = new Form("Hanspee");
		// hi.addComponent(new Label("Smert is a group of smart people."));
		Button q = new Button("Q");
		keyboard.add(q);
		Button w = new Button("W");
		keyboard.add(w);
		Button e = new Button("E");
		keyboard.add(e);
		Button r = new Button("R");
		keyboard.add(r);
		Button t = new Button("T");
		keyboard.add(t);
		Button y = new Button("Y");
		keyboard.add(y);
		Button u = new Button("U");
		keyboard.add(u);
		Button i = new Button("I");
		keyboard.add(i);
		Button o = new Button("O");
		keyboard.add(o);
		Button p = new Button("P");
		keyboard.add(p);
		Button a = new Button("A");
		keyboard.add(a);
		Button s = new Button("S");
		keyboard.add(s);
		Button d = new Button("D");
		keyboard.add(d);
		Button f = new Button("F");
		keyboard.add(f);
		Button g = new Button("G");
		keyboard.add(g);
		Button h = new Button("H");
		keyboard.add(h);
		Button j = new Button("J");
		keyboard.add(j);
		Button k = new Button("K");
		keyboard.add(k);
		Button l = new Button("L");
		keyboard.add(l);
		Button z = new Button("Z");
		keyboard.add(z);
		Button x = new Button("X");
		keyboard.add(x);
		Button c = new Button("C");
		keyboard.add(c);
		Button v = new Button("V");
		keyboard.add(v);
		Button b = new Button("B");
		keyboard.add(b);
		Button n = new Button("N");
		keyboard.add(n);
		Button m = new Button("M");
		keyboard.add(m);
		// b.addActionListener(e -> Dialog.show("Hanspee", "Smert is a group of
		// smart people", "OK", null));
		keyboard.show();
    }

    //test224
    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
